/**
 * Extractor tests, in two halves.
 *
 * The unit half is synthetic and runs anywhere. It covers the rules themselves.
 *
 * The parity half runs against REAL transcripts on this machine, driven by
 * fixtures.local.json, which is gitignored so real ticket keys never enter git.
 * Copy fixtures.example.json, or run `bun run fixtures.ts`, to create one.
 *
 * That half matters because aiTitle is an undocumented Claude Code internal
 * (observed on 2.1.233 / 2.1.239). If a version renames or drops it, extraction
 * silently degrades and nothing errors anywhere. Checking real files turns that
 * into a failing test. Without fixtures.local.json those tests skip, and the
 * suite says so rather than pretending to have covered it.
 */

import { describe, expect, test, beforeAll } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import {
  extractFromText,
  extractSession,
  proseFromText,
  agentNameFromText,
  prsFromText,
  scanFull,
  isTicketKey,
  TICKET_PREFIXES,
} from "./extract.ts";
import { scanSessions, type SessionMeta } from "./scan.ts";

interface Fixtures {
  /** session id prefix -> ticket the extractor must return */
  mustMatch: Record<string, string>;
  /** session id prefix -> why it must return null */
  mustNotMatch: Record<string, string>;
  /** session id prefix -> the canonical name Claude carries for it */
  agentNames: Record<string, string>;
  /** session id prefix -> pull request urls opened in it */
  prs: Record<string, string[]>;
}

// Resolved synchronously at module load so describe.skipIf can see it. An async
// check in beforeAll runs after registration, and the parity block would then
// report as passing when it had in fact done nothing.
const FIXTURE_PATH = new URL("./fixtures.local.json", import.meta.url).pathname;
const HAS_FIXTURES = existsSync(FIXTURE_PATH);

let fixtures: Fixtures = { mustMatch: {}, mustNotMatch: {}, agentNames: {}, prs: {} };
let sessions: SessionMeta[] = [];
const find = (prefix: string) => sessions.find((s) => s.id.startsWith(prefix));

if (!HAS_FIXTURES) {
  console.warn(
    "\n  fixtures.local.json missing — real-corpus parity tests SKIPPED." +
      "\n  Copy fixtures.example.json or run `bun run fixtures.ts` to enable them." +
      "\n  Without it, an aiTitle format change in Claude Code will NOT be caught.\n",
  );
}

beforeAll(async () => {
  if (!HAS_FIXTURES) return;
  const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Partial<Fixtures>;
  fixtures = {
    mustMatch: raw.mustMatch ?? {},
    mustNotMatch: raw.mustNotMatch ?? {},
    agentNames: raw.agentNames ?? {},
    prs: raw.prs ?? {},
  };
  sessions = await scanSessions();
});

/** Keys are built from the configured prefix so these tests pass for any project. */
const P = TICKET_PREFIXES[0]!;
const key = (n: number) => `${P}-${n}`;

describe("extractFromText", () => {
  const jsonl = (...records: unknown[]) => records.map((r) => JSON.stringify(r)).join("\n");

  test("aiTitle wins when it carries a ticket", () => {
    const text = jsonl(
      { type: "user", message: { content: `Check ${key(999)} in Jira, let's plan it` } },
      { aiTitle: `Plan ${key(101)} Jira ticket with scanner work` },
    );
    expect(extractFromText(text)).toEqual({
      ticket: `${key(101)}`,
      name: `Plan ${key(101)} Jira ticket with scanner work`,
      source: "aiTitle",
    });
  });

  test("falls back to the opener when aiTitle has no ticket", () => {
    const text = jsonl(
      { aiTitle: "Complete the policy step in the modules repo" },
      { type: "user", message: { content: `Check ${key(102)} in Jira. We need to finish it.` } },
    );
    const got = extractFromText(text);
    expect(got.ticket).toBe(`${key(102)}`);
    expect(got.source).toBe("opener");
    expect(got.name).toBe("Complete the policy step in the modules repo");
  });

  test("opener must be anchored — a mid-sentence mention is not intent", () => {
    const text = jsonl({ type: "user", message: { content: `While deploying I should check ${key(103)} at some point` } });
    expect(extractFromText(text).ticket).toBeNull();
  });

  test("skill preambles are not treated as the first user message", () => {
    const text = jsonl(
      { type: "user", message: { content: "Base directory for this skill: /home/dev/.claude/skills/example" } },
      { type: "user", message: { content: `Read ${key(104)} in Jira, let's implement it.` } },
    );
    expect(extractFromText(text).ticket).toBe(`${key(104)}`);
  });

  test("caveat and interrupt wrappers are skipped", () => {
    const text = jsonl(
      { type: "user", message: { content: "Caveat: The messages below were generated by the user while running local commands." } },
      { type: "user", message: { content: "[Request interrupted by user for tool use]" } },
      { type: "user", message: { content: `look at ${key(105)} in Jira. Let's write a plan for it` } },
    );
    expect(extractFromText(text).ticket).toBe(`${key(105)}`);
  });

  test("handles content as a block array, not just a string", () => {
    const text = jsonl({
      type: "user",
      message: { content: [{ type: "text", text: `Read ${key(106)} in Jira, let's implement it` }] },
    });
    expect(extractFromText(text).ticket).toBe(`${key(106)}`);
  });

  test("unparseable lines are skipped, not fatal", () => {
    const text = [
      "{ this is not json",
      JSON.stringify({ aiTitle: `Implement ${key(107)} from Jira` }),
      '{"truncated": ', // a sliced read always ends mid-line
    ].join("\n");
    expect(extractFromText(text).ticket).toBe(`${key(107)}`);
  });

  test("the slug field must never be used as a ticket source", () => {
    // The real failure this guards: a chore session whose slug preserves a stale
    // opener while aiTitle reflects what the session actually did. Regexing raw
    // bytes matches the slug and pre-fills a ticket on unrelated work.
    const text = jsonl(
      { slug: `check-${P.toLowerCase()}-108-in-jira-recursive-quasar` },
      { aiTitle: "Fetch and pull main branch updates" },
      { type: "user", message: { content: "git fetch and pull main up to date" } },
    );
    expect(extractFromText(text).ticket).toBeNull();
  });

  test("no ticket anywhere yields a name but no ticket", () => {
    const text = jsonl({ aiTitle: "Repository disk space cleanup" });
    expect(extractFromText(text)).toEqual({
      ticket: null,
      name: "Repository disk space cleanup",
      source: null,
    });
  });

  test("empty input does not throw", () => {
    expect(extractFromText("")).toEqual({ ticket: null, name: null, source: null });
  });

  test("UTF-8 style tokens are not mistaken for tickets", () => {
    const text = jsonl({ aiTitle: "Fix UTF-8 encoding and HTTP-2 negotiation" });
    expect(extractFromText(text).ticket).toBeNull();
  });

  test("isTicketKey accepts a whole key and rejects a substring", () => {
    expect(isTicketKey(`${key(101)}`)).toBe(true);
    expect(isTicketKey(`see ${key(101)}`)).toBe(false);
    expect(isTicketKey("UTF-8")).toBe(false);
  });
});

describe("proseFromText", () => {
  const jsonl = (...records: unknown[]) => records.map((r) => JSON.stringify(r)).join("\n");

  test("keeps what both sides said", () => {
    const text = jsonl(
      { type: "user", message: { content: "the trivy exemption keeps failing" } },
      { type: "assistant", message: { content: "the scanner needs an allowlist entry" } },
    );
    expect(proseFromText(text)).toBe("the trivy exemption keeps failing\nthe scanner needs an allowlist entry");
  });

  test("tool output stays out — it would match the file, not the session", () => {
    const text = jsonl({
      type: "assistant",
      message: {
        content: [
          { type: "text", text: "running the scan now" },
          { type: "tool_use", name: "Bash", input: { command: "grep -r nosuchmarker ." } },
        ],
      },
    });
    const prose = proseFromText(text);
    expect(prose).toBe("running the scan now");
    expect(prose).not.toContain("nosuchmarker");
  });

  test("tool results stay out too", () => {
    const text = jsonl({
      type: "user",
      message: { content: [{ type: "tool_result", content: "nosuchmarker: 4 occurrences" }] },
    });
    expect(proseFromText(text)).toBe("");
  });

  test("harness boilerplate is dropped, so it cannot match every query", () => {
    const text = jsonl(
      { type: "user", message: { content: "Caveat: The messages below were generated by the user while running local commands." } },
      { type: "user", message: { content: "[Request interrupted by user for tool use]" } },
      { type: "user", message: { content: "now check the deployment logs please" } },
    );
    expect(proseFromText(text)).toBe("now check the deployment logs please");
  });

  test("system-reminder blocks are stripped along with their contents", () => {
    const text = jsonl({
      type: "user",
      message: { content: "real question here <system-reminder>injected nosuchmarker guidance</system-reminder>" },
    });
    const prose = proseFromText(text);
    expect(prose).toContain("real question here");
    expect(prose).not.toContain("nosuchmarker");
  });

  test("a runaway transcript is capped rather than held whole", () => {
    const big = "lorem ipsum dolor ".repeat(120_000); // ~2.1MB, over the 1MB cap
    const text = jsonl({ type: "user", message: { content: big } });
    expect(proseFromText(text).length).toBe(1024 * 1024);
  });

  test("the cap clears the largest session measured on the real corpus", () => {
    // 735KB was the maximum. A cap below it truncates real debugging sessions.
    const text = jsonl({ type: "user", message: { content: "x ".repeat(400_000) } }); // ~800KB
    expect(proseFromText(text).length).toBeGreaterThan(735 * 1024);
  });

  test("records that are neither user nor assistant contribute nothing", () => {
    const text = jsonl(
      { aiTitle: "Repository disk space cleanup" },
      { slug: "some-nosuchmarker-slug" },
      { type: "summary", summary: "nosuchmarker recap" },
    );
    expect(proseFromText(text)).toBe("");
  });

  test("unparseable and empty lines are skipped, not fatal", () => {
    const text = [
      "{ this is not json",
      "",
      JSON.stringify({ type: "user", message: { content: "the surviving line" } }),
      '{"truncated": ',
    ].join("\n");
    expect(proseFromText(text)).toBe("the surviving line");
  });

  test("empty input does not throw", () => {
    expect(proseFromText("")).toBe("");
  });
});

describe("agentNameFromText", () => {
  const jsonl = (...records: unknown[]) => records.map((r) => JSON.stringify(r)).join("\n");

  test("returns the name Claude carries, without an @", () => {
    const text = jsonl({ type: "agent-name", agentName: "api-worker" });
    expect(agentNameFromText(text)).toBe("api-worker");
  });

  test("the LAST name wins, because sessions get renamed mid-run", () => {
    // Three local transcripts do exactly this. Taking the first would report a
    // name the session no longer answers to.
    const text = jsonl(
      { type: "agent-name", agentName: "first-name" },
      { type: "user", message: { content: "work happens" } },
      { type: "agent-name", agentName: "second-name" },
      { type: "agent-name", agentName: "third-name" },
    );
    expect(agentNameFromText(text)).toBe("third-name");
  });

  test("a session with no agent-name record has no name", () => {
    expect(agentNameFromText(jsonl({ type: "ai-title", aiTitle: "Some summary" }))).toBeNull();
  });

  test("an empty or whitespace name is no name, not an empty string", () => {
    expect(agentNameFromText(jsonl({ type: "agent-name", agentName: "   " }))).toBeNull();
    expect(agentNameFromText(jsonl({ type: "agent-name", agentName: "" }))).toBeNull();
  });

  test("a non-string name is ignored", () => {
    expect(agentNameFromText(jsonl({ type: "agent-name", agentName: 42 }))).toBeNull();
  });

  test("an earlier real name survives a later malformed one", () => {
    const text = jsonl({ type: "agent-name", agentName: "real" }, { type: "agent-name" });
    expect(agentNameFromText(text)).toBe("real");
  });

  test("unparseable and truncated lines are skipped, not fatal", () => {
    const text = `{ not json\n${JSON.stringify({ type: "agent-name", agentName: "survives" })}\n{"type":"agent-name",`;
    expect(agentNameFromText(text)).toBe("survives");
  });

  test("a name recorded past the prose cap is still found", () => {
    // The direct regression guard for folding this into proseFromText, which
    // stops at PROSE_CAP. 15 of 24 named sessions record the name beyond 512KB.
    const filler = Array.from({ length: 400 }, (_, i) =>
      JSON.stringify({ type: "user", message: { content: `padding line ${i} `.repeat(200) } }),
    ).join("\n");
    const text = `${filler}\n${JSON.stringify({ type: "agent-name", agentName: "late-name" })}`;
    expect(text.length).toBeGreaterThan(1024 * 1024);
    expect(agentNameFromText(text)).toBe("late-name");
  });
});

describe("prsFromText", () => {
  const jsonl = (...records: unknown[]) => records.map((r) => JSON.stringify(r)).join("\n");
  const prLink = (n: number, timestamp: string, repository = "owner/repo") => ({
    type: "pr-link",
    prNumber: n,
    prRepository: repository,
    prUrl: `https://github.com/${repository}/pull/${n}`,
    timestamp,
  });

  test("reads a pull request out of the transcript's own record", () => {
    expect(prsFromText(jsonl(prLink(7, "2026-09-01T10:00:00.000Z")))).toEqual([
      {
        number: 7,
        repository: "owner/repo",
        url: "https://github.com/owner/repo/pull/7",
        firstSeen: "2026-09-01T10:00:00.000Z",
      },
    ]);
  });

  test("repeats are deduped by url and keep the EARLIEST timestamp", () => {
    // The record is rewritten every turn: 3170 of them locally for 87 real PRs.
    // The first sighting is when the PR was opened, which is the useful one.
    const text = jsonl(
      prLink(7, "2026-09-01T12:00:00.000Z"),
      prLink(7, "2026-09-01T10:00:00.000Z"),
      prLink(7, "2026-09-02T09:00:00.000Z"),
    );
    const prs = prsFromText(text);
    expect(prs).toHaveLength(1);
    expect(prs[0]!.firstSeen).toBe("2026-09-01T10:00:00.000Z");
  });

  test("several pull requests come back newest first", () => {
    const text = jsonl(
      prLink(1, "2026-09-01T10:00:00.000Z"),
      prLink(3, "2026-09-03T10:00:00.000Z"),
      prLink(2, "2026-09-02T10:00:00.000Z"),
    );
    expect(prsFromText(text).map((p) => p.number)).toEqual([3, 2, 1]);
  });

  test("pull requests across repositories are all kept", () => {
    const text = jsonl(
      prLink(1, "2026-09-01T10:00:00.000Z", "owner/one"),
      prLink(1, "2026-09-02T10:00:00.000Z", "owner/two"),
    );
    expect(prsFromText(text).map((p) => p.repository)).toEqual(["owner/two", "owner/one"]);
  });

  test("a record missing a url, repository or number is skipped", () => {
    const text = jsonl(
      { type: "pr-link", prNumber: 1, prRepository: "owner/repo" },
      { type: "pr-link", prNumber: 2, prUrl: "https://github.com/owner/repo/pull/2" },
      { type: "pr-link", prRepository: "owner/repo", prUrl: "https://github.com/owner/repo/pull/3" },
      prLink(4, "2026-09-01T10:00:00.000Z"),
    );
    expect(prsFromText(text).map((p) => p.number)).toEqual([4]);
  });

  test("unparseable and truncated lines are skipped, not fatal", () => {
    const text = `{ not json\n${JSON.stringify(prLink(9, "2026-09-01T10:00:00.000Z"))}\n{"type":"pr-link",`;
    expect(prsFromText(text).map((p) => p.number)).toEqual([9]);
  });

  test("a session that opened nothing yields an empty list", () => {
    expect(prsFromText(jsonl({ type: "user", message: { content: "no pull requests here" } }))).toEqual([]);
  });

  test("a pull request recorded past the prose cap is still found", () => {
    // 22 of 23 sessions with PRs record the first one beyond 512KB.
    const filler = Array.from({ length: 400 }, (_, i) =>
      JSON.stringify({ type: "user", message: { content: `padding line ${i} `.repeat(200) } }),
    ).join("\n");
    const text = `${filler}\n${JSON.stringify(prLink(99, "2026-09-01T10:00:00.000Z"))}`;
    expect(text.length).toBeGreaterThan(1024 * 1024);
    expect(prsFromText(text).map((p) => p.number)).toEqual([99]);
  });
});

describe("scanFull", () => {
  test("an unreadable file yields an empty scan rather than throwing", async () => {
    expect(await scanFull("/does/not/exist.jsonl")).toEqual({
      mentions: new Set(),
      prose: "",
      agentName: null,
      prs: [],
    });
  });
});

describe.skipIf(!HAS_FIXTURES)("parity against real transcripts", () => {
  test("the corpus is present, otherwise every assertion below is vacuous", () => {
    expect(sessions.length).toBeGreaterThan(0);
    const present = Object.keys(fixtures.mustMatch).filter(find).length;
    const total = Object.keys(fixtures.mustMatch).length;
    // Sessions age off disk over time; wholesale loss means the fixture is stale.
    expect(present).toBeGreaterThanOrEqual(Math.ceil(total * 0.6));
  });

  test("every fixture session resolves to its expected ticket", async () => {
    const wrong: string[] = [];
    for (const [prefix, expected] of Object.entries(fixtures.mustMatch)) {
      const session = find(prefix);
      if (!session) continue; // aged off disk; the guard above catches wholesale loss
      const got = await extractSession(session.path);
      if (got.ticket !== expected) wrong.push(`${prefix}: expected ${expected}, got ${got.ticket}`);
      else expect(isTicketKey(got.ticket)).toBe(true);
    }
    expect(wrong).toEqual([]);
  });

  test("chore sessions return no ticket, even though their bytes mention one", async () => {
    const leaked: string[] = [];
    for (const [prefix, why] of Object.entries(fixtures.mustNotMatch)) {
      const session = find(prefix);
      if (!session) continue;
      const got = await extractSession(session.path);
      if (got.ticket !== null) leaked.push(`${prefix} pre-filled ${got.ticket} — ${why}`);
    }
    expect(leaked).toEqual([]);
  });

  test("every session yields either a ticket or a usable name", async () => {
    let nameless = 0;
    for (const s of sessions) {
      const { ticket, name } = await extractSession(s.path);
      if (!ticket && !name) nameless++;
    }
    // A handful of aborted sessions legitimately have neither.
    expect(nameless).toBeLessThanOrEqual(Math.ceil(sessions.length * 0.3));
  });

  test("every fixture session still carries the name Claude gave it", async () => {
    const wrong: string[] = [];
    for (const [prefix, expected] of Object.entries(fixtures.agentNames)) {
      const session = find(prefix);
      if (!session) continue;
      const { agentName } = await scanFull(session.path);
      if (agentName !== expected) wrong.push(`${prefix}: expected ${expected}, got ${agentName}`);
    }
    expect(wrong).toEqual([]);
  });

  test("no canonical name arrives with an @ already on it", async () => {
    // The @ is Claude Code's display prefix, not part of the value. If that ever
    // changes, the page would render "@@name" and nothing else would complain.
    const prefixed: string[] = [];
    for (const s of sessions) {
      const { agentName } = await scanFull(s.path);
      if (agentName?.startsWith("@")) prefixed.push(`${s.id.slice(0, 8)}: ${agentName}`);
    }
    expect(prefixed).toEqual([]);
  });

  test("every fixture session still lists the pull requests it opened", async () => {
    // Subset, not equality. A live session keeps opening pull requests — the
    // session running this suite is itself in the corpus — so pinning an exact
    // list makes the fixture expire the moment anyone opens another PR, which
    // fails as a regression when nothing regressed. A PR is never un-opened, so
    // "everything we recorded is still found" is the property that holds.
    // Extra entries are covered by the dedupe test below and by the unit tests.
    const missing: string[] = [];
    for (const [prefix, expected] of Object.entries(fixtures.prs)) {
      const session = find(prefix);
      if (!session) continue;
      const { prs } = await scanFull(session.path);
      const got = new Set(prs.map((p) => p.url));
      const gone = expected.filter((url) => !got.has(url));
      if (gone.length) missing.push(`${prefix}: no longer finds ${gone.join(", ")}`);
    }
    expect(missing).toEqual([]);
  });

  test("pull requests are deduped across the real corpus, not just in the unit tests", async () => {
    const offenders: string[] = [];
    let total = 0;
    for (const s of sessions) {
      const { prs } = await scanFull(s.path);
      total += prs.length;
      if (new Set(prs.map((p) => p.url)).size !== prs.length) offenders.push(s.id.slice(0, 8));
    }
    expect(offenders).toEqual([]);
    // The records repeat thousands of times; a dedupe that silently stopped
    // working would show up here as an implausible count, not as a wrong url.
    expect(total).toBeLessThan(sessions.length * 40);
  });
});
