/**
 * Extractor tests, in two halves.
 *
 * The unit half is synthetic and runs anywhere. It covers the rules themselves.
 *
 * The parity half runs against REAL transcripts on this machine, driven by
 * fixtures.local.json, which is gitignored so real ticket keys never enter git.
 * Copy fixtures.example.json, or run `bun run fixtures.ts`, to create one.
 *
 * That half matters because aiTitle is an undocumented Claude Code internal
 * (observed on 2.1.233 / 2.1.239). If a version renames or drops it, extraction
 * silently degrades and nothing errors anywhere. Checking real files turns that
 * into a failing test. Without fixtures.local.json those tests skip, and the
 * suite says so rather than pretending to have covered it.
 */

import { describe, expect, test, beforeAll } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { extractFromText, extractSession, proseFromText, isTicketKey, TICKET_PREFIXES } from "./extract.ts";
import { scanSessions, type SessionMeta } from "./scan.ts";

interface Fixtures {
  /** session id prefix -> ticket the extractor must return */
  mustMatch: Record<string, string>;
  /** session id prefix -> why it must return null */
  mustNotMatch: Record<string, string>;
}

// Resolved synchronously at module load so describe.skipIf can see it. An async
// check in beforeAll runs after registration, and the parity block would then
// report as passing when it had in fact done nothing.
const FIXTURE_PATH = new URL("./fixtures.local.json", import.meta.url).pathname;
const HAS_FIXTURES = existsSync(FIXTURE_PATH);

let fixtures: Fixtures = { mustMatch: {}, mustNotMatch: {} };
let sessions: SessionMeta[] = [];
const find = (prefix: string) => sessions.find((s) => s.id.startsWith(prefix));

if (!HAS_FIXTURES) {
  console.warn(
    "\n  fixtures.local.json missing — real-corpus parity tests SKIPPED." +
      "\n  Copy fixtures.example.json or run `bun run fixtures.ts` to enable them." +
      "\n  Without it, an aiTitle format change in Claude Code will NOT be caught.\n",
  );
}

beforeAll(async () => {
  if (!HAS_FIXTURES) return;
  const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Partial<Fixtures>;
  fixtures = { mustMatch: raw.mustMatch ?? {}, mustNotMatch: raw.mustNotMatch ?? {} };
  sessions = await scanSessions();
});

/** Keys are built from the configured prefix so these tests pass for any project. */
const P = TICKET_PREFIXES[0]!;
const key = (n: number) => `${P}-${n}`;

describe("extractFromText", () => {
  const jsonl = (...records: unknown[]) => records.map((r) => JSON.stringify(r)).join("\n");

  test("aiTitle wins when it carries a ticket", () => {
    const text = jsonl(
      { type: "user", message: { content: `Check ${key(999)} in Jira, let's plan it` } },
      { aiTitle: `Plan ${key(101)} Jira ticket with scanner work` },
    );
    expect(extractFromText(text)).toEqual({
      ticket: `${key(101)}`,
      name: `Plan ${key(101)} Jira ticket with scanner work`,
      source: "aiTitle",
    });
  });

  test("falls back to the opener when aiTitle has no ticket", () => {
    const text = jsonl(
      { aiTitle: "Complete the policy step in the modules repo" },
      { type: "user", message: { content: `Check ${key(102)} in Jira. We need to finish it.` } },
    );
    const got = extractFromText(text);
    expect(got.ticket).toBe(`${key(102)}`);
    expect(got.source).toBe("opener");
    expect(got.name).toBe("Complete the policy step in the modules repo");
  });

  test("opener must be anchored — a mid-sentence mention is not intent", () => {
    const text = jsonl({ type: "user", message: { content: `While deploying I should check ${key(103)} at some point` } });
    expect(extractFromText(text).ticket).toBeNull();
  });

  test("skill preambles are not treated as the first user message", () => {
    const text = jsonl(
      { type: "user", message: { content: "Base directory for this skill: /home/dev/.claude/skills/example" } },
      { type: "user", message: { content: `Read ${key(104)} in Jira, let's implement it.` } },
    );
    expect(extractFromText(text).ticket).toBe(`${key(104)}`);
  });

  test("caveat and interrupt wrappers are skipped", () => {
    const text = jsonl(
      { type: "user", message: { content: "Caveat: The messages below were generated by the user while running local commands." } },
      { type: "user", message: { content: "[Request interrupted by user for tool use]" } },
      { type: "user", message: { content: `look at ${key(105)} in Jira. Let's write a plan for it` } },
    );
    expect(extractFromText(text).ticket).toBe(`${key(105)}`);
  });

  test("handles content as a block array, not just a string", () => {
    const text = jsonl({
      type: "user",
      message: { content: [{ type: "text", text: `Read ${key(106)} in Jira, let's implement it` }] },
    });
    expect(extractFromText(text).ticket).toBe(`${key(106)}`);
  });

  test("unparseable lines are skipped, not fatal", () => {
    const text = [
      "{ this is not json",
      JSON.stringify({ aiTitle: `Implement ${key(107)} from Jira` }),
      '{"truncated": ', // a sliced read always ends mid-line
    ].join("\n");
    expect(extractFromText(text).ticket).toBe(`${key(107)}`);
  });

  test("the slug field must never be used as a ticket source", () => {
    // The real failure this guards: a chore session whose slug preserves a stale
    // opener while aiTitle reflects what the session actually did. Regexing raw
    // bytes matches the slug and pre-fills a ticket on unrelated work.
    const text = jsonl(
      { slug: `check-${P.toLowerCase()}-108-in-jira-recursive-quasar` },
      { aiTitle: "Fetch and pull main branch updates" },
      { type: "user", message: { content: "git fetch and pull main up to date" } },
    );
    expect(extractFromText(text).ticket).toBeNull();
  });

  test("no ticket anywhere yields a name but no ticket", () => {
    const text = jsonl({ aiTitle: "Repository disk space cleanup" });
    expect(extractFromText(text)).toEqual({
      ticket: null,
      name: "Repository disk space cleanup",
      source: null,
    });
  });

  test("empty input does not throw", () => {
    expect(extractFromText("")).toEqual({ ticket: null, name: null, source: null });
  });

  test("UTF-8 style tokens are not mistaken for tickets", () => {
    const text = jsonl({ aiTitle: "Fix UTF-8 encoding and HTTP-2 negotiation" });
    expect(extractFromText(text).ticket).toBeNull();
  });

  test("isTicketKey accepts a whole key and rejects a substring", () => {
    expect(isTicketKey(`${key(101)}`)).toBe(true);
    expect(isTicketKey(`see ${key(101)}`)).toBe(false);
    expect(isTicketKey("UTF-8")).toBe(false);
  });
});

describe("proseFromText", () => {
  const jsonl = (...records: unknown[]) => records.map((r) => JSON.stringify(r)).join("\n");

  test("keeps what both sides said", () => {
    const text = jsonl(
      { type: "user", message: { content: "the trivy exemption keeps failing" } },
      { type: "assistant", message: { content: "the scanner needs an allowlist entry" } },
    );
    expect(proseFromText(text)).toBe("the trivy exemption keeps failing\nthe scanner needs an allowlist entry");
  });

  test("tool output stays out — it would match the file, not the session", () => {
    const text = jsonl({
      type: "assistant",
      message: {
        content: [
          { type: "text", text: "running the scan now" },
          { type: "tool_use", name: "Bash", input: { command: "grep -r nosuchmarker ." } },
        ],
      },
    });
    const prose = proseFromText(text);
    expect(prose).toBe("running the scan now");
    expect(prose).not.toContain("nosuchmarker");
  });

  test("tool results stay out too", () => {
    const text = jsonl({
      type: "user",
      message: { content: [{ type: "tool_result", content: "nosuchmarker: 4 occurrences" }] },
    });
    expect(proseFromText(text)).toBe("");
  });

  test("harness boilerplate is dropped, so it cannot match every query", () => {
    const text = jsonl(
      { type: "user", message: { content: "Caveat: The messages below were generated by the user while running local commands." } },
      { type: "user", message: { content: "[Request interrupted by user for tool use]" } },
      { type: "user", message: { content: "now check the deployment logs please" } },
    );
    expect(proseFromText(text)).toBe("now check the deployment logs please");
  });

  test("system-reminder blocks are stripped along with their contents", () => {
    const text = jsonl({
      type: "user",
      message: { content: "real question here <system-reminder>injected nosuchmarker guidance</system-reminder>" },
    });
    const prose = proseFromText(text);
    expect(prose).toContain("real question here");
    expect(prose).not.toContain("nosuchmarker");
  });

  test("a runaway transcript is capped rather than held whole", () => {
    const big = "lorem ipsum dolor ".repeat(120_000); // ~2.1MB, over the 1MB cap
    const text = jsonl({ type: "user", message: { content: big } });
    expect(proseFromText(text).length).toBe(1024 * 1024);
  });

  test("the cap clears the largest session measured on the real corpus", () => {
    // 735KB was the maximum. A cap below it truncates real debugging sessions.
    const text = jsonl({ type: "user", message: { content: "x ".repeat(400_000) } }); // ~800KB
    expect(proseFromText(text).length).toBeGreaterThan(735 * 1024);
  });

  test("records that are neither user nor assistant contribute nothing", () => {
    const text = jsonl(
      { aiTitle: "Repository disk space cleanup" },
      { slug: "some-nosuchmarker-slug" },
      { type: "summary", summary: "nosuchmarker recap" },
    );
    expect(proseFromText(text)).toBe("");
  });

  test("unparseable and empty lines are skipped, not fatal", () => {
    const text = [
      "{ this is not json",
      "",
      JSON.stringify({ type: "user", message: { content: "the surviving line" } }),
      '{"truncated": ',
    ].join("\n");
    expect(proseFromText(text)).toBe("the surviving line");
  });

  test("empty input does not throw", () => {
    expect(proseFromText("")).toBe("");
  });
});

describe.skipIf(!HAS_FIXTURES)("parity against real transcripts", () => {
  test("the corpus is present, otherwise every assertion below is vacuous", () => {
    expect(sessions.length).toBeGreaterThan(0);
    const present = Object.keys(fixtures.mustMatch).filter(find).length;
    const total = Object.keys(fixtures.mustMatch).length;
    // Sessions age off disk over time; wholesale loss means the fixture is stale.
    expect(present).toBeGreaterThanOrEqual(Math.ceil(total * 0.6));
  });

  test("every fixture session resolves to its expected ticket", async () => {
    const wrong: string[] = [];
    for (const [prefix, expected] of Object.entries(fixtures.mustMatch)) {
      const session = find(prefix);
      if (!session) continue; // aged off disk; the guard above catches wholesale loss
      const got = await extractSession(session.path);
      if (got.ticket !== expected) wrong.push(`${prefix}: expected ${expected}, got ${got.ticket}`);
      else expect(isTicketKey(got.ticket)).toBe(true);
    }
    expect(wrong).toEqual([]);
  });

  test("chore sessions return no ticket, even though their bytes mention one", async () => {
    const leaked: string[] = [];
    for (const [prefix, why] of Object.entries(fixtures.mustNotMatch)) {
      const session = find(prefix);
      if (!session) continue;
      const got = await extractSession(session.path);
      if (got.ticket !== null) leaked.push(`${prefix} pre-filled ${got.ticket} — ${why}`);
    }
    expect(leaked).toEqual([]);
  });

  test("every session yields either a ticket or a usable name", async () => {
    let nameless = 0;
    for (const s of sessions) {
      const { ticket, name } = await extractSession(s.path);
      if (!ticket && !name) nameless++;
    }
    // A handful of aborted sessions legitimately have neither.
    expect(nameless).toBeLessThanOrEqual(Math.ceil(sessions.length * 0.3));
  });
});
