/**
 * Generates a starting point for fixtures.local.json from the sessions on this
 * machine, so you do not have to assemble it by hand.
 *
 *   bun run fixtures.ts            print to stdout
 *   bun run fixtures.ts --write    write fixtures.local.json (refuses to clobber)
 *
 * What it produces is a DRAFT. The extractor's own output seeds it, so it can
 * only ever agree with itself. Go through the list and correct anything wrong
 * before trusting it, especially the mustNotMatch half: that is the part which
 * catches an implementation regressing to a raw-byte regex.
 *
 * fixtures.local.json is gitignored. Real ticket keys never enter git.
 */

import { scanSessions } from "./scan.ts";
import { extractSession } from "./extract.ts";

const OUT = "fixtures.local.json";

const sessions = await scanSessions();
if (sessions.length === 0) {
  console.error("No sessions found under ~/.claude/projects — nothing to generate.");
  process.exit(1);
}

const mustMatch: Record<string, string> = {};
const mustNotMatch: Record<string, string> = {};

for (const s of sessions) {
  const { ticket, name, source } = await extractSession(s.path);
  const key = s.id.slice(0, 8);
  if (ticket) mustMatch[key] = ticket;
  else if (name) mustNotMatch[key] = `no ticket intent — "${name.slice(0, 60)}"`;
}

const draft = {
  _comment: "Local only, gitignored. DRAFT generated by fixtures.ts — verify before trusting.",
  mustMatch,
  mustNotMatch,
};

const json = JSON.stringify(draft, null, 2) + "\n";

if (!Bun.argv.includes("--write")) {
  console.log(json);
  console.error(
    `\n# ${Object.keys(mustMatch).length} ticketed, ${Object.keys(mustNotMatch).length} without.` +
      `\n# Review, then rerun with --write, or paste into ${OUT} yourself.`,
  );
  process.exit(0);
}

if (await Bun.file(OUT).exists()) {
  console.error(`${OUT} already exists. Delete it first if you really mean to regenerate.`);
  process.exit(1);
}
await Bun.write(OUT, json);
console.log(`Wrote ${OUT}: ${Object.keys(mustMatch).length} ticketed, ${Object.keys(mustNotMatch).length} without.`);
console.log("Review it. The generator agrees with the extractor by construction, so it proves nothing until you check it.");
